#' Approximate the covariance matrix via factor analysis.
#'
#' @param returns A matrix of stock returns.
#' @param model An object of S4 class 'facmodel' generated by
#' the function `fit.factor.model()`.
#'
#' @return The approximated covariance matrix, covariance of errors and factors.
#' @export
#' @importFrom magrittr %>%
approx.covar <- function(returns,model){
  n <- ncol(returns)
  scores <- model@scores
  loadings <- model@loadings
  mean <- rowMeans(returns)
  error <- returns - mean %*% t(rep(1,n)) - t(loadings)%*%scores
  f.covar <- scores %*% t(scores) * 1/n
  #We keep only the diagonal elements.
  error.covar <- error %*% t(error) * 1/n
  error.covar <- diag(diag(error.covar))
  covar <- t(loadings) %*% f.covar %*% loadings + error.covar
  return(list(covar = covar, error.covar = error.covar, f.covar = f.covar,error=error))
}
